name: "Prepare for Build with Apache Maven"
description: "Checks out code and installs Java in preparation for Maven build"

branding:
  icon: more-horizontal
  color: purple

inputs:
  java-version:
    description: Java version
    required: true
    default: 17
  checkout-branch:
    description: git branch to checkout
    required: false
    default: ''
  gpg-private-key:
    description: GPG private key for signing
    required: false
    default: ''
  fetch-depth:
    description: Number of commits to fetch
    required: false
    default: 1

runs:
  using: "composite"
  steps:
    - id: checkout-code
      name: Checkout code
      uses: actions/checkout@v7
      with:
        ref: ${{ inputs.checkout-branch }}
        fetch-depth: ${{ inputs.fetch-depth }}
    - id: setup-java
      name: Set up JDK
      uses: actions/setup-java@v6
      with:
        distribution: temurin
        java-version: ${{ inputs.java-version }}
        cache: maven
        server-id: central
        server-username-env-var: NEXUS_USERNAME
        server-password-env-var: NEXUS_PASSWORD
        gpg-passphrase-env-var: GPG_PASSPHRASE
        gpg-private-key: ${{ inputs.gpg-private-key }}
    - id: show-environment
      name: Show environment
      shell: bash
      run: |
        # Show environment
        echo ">>>> Operating system:"
        echo "  ${{ runner.os }}"
        echo ">>>> GitHub:"
        echo "  github.repository: ${{ github.repository }}"
        echo "  github.ref: ${{ github.head_ref || github.ref }}"
        echo "  github.sha: ${{ github.sha }}"
        echo ">>>> Java:"
        java -version
        echo ">>>> Maven:"
        mvn -v
        echo ">>>> Maven settings.xml:"
        cat ~/.m2/settings.xml ; echo
        echo ">>>> Maven toolchains.xml:"
        cat ~/.m2/toolchains.xml ; echo
        echo ">>>> Graphviz:"
        which dot || echo "Graphviz not installed"
        echo ">>>> GPG:"
        gpg --version
        gpgconf --list-components
        echo test | gpg --clearsign
        gpg --list-secret-keys --keyid-format LONG
        echo
