name: "Prepare for Build with Apache Maven"
description: "Checks out code and installs Java in preparation for Maven build"

branding:
  icon: more-horizontal
  color: purple

inputs:
  java-version:
    description: Java version
    required: true
    default: 8
  checkout-branch:
    description: git branch to checkout
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - id: maximize-build-space
      name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: '8192'
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        remove-codeql: 'true'
        remove-docker-images: 'true'
    - id: restart-docker
      name: Restart Docker
      if: runner.os == 'Linux'
      shell: bash
      run: |
        # Restart Docker to take into account additional disk space
        # https://stackoverflow.com/a/71113148/100856
        sudo systemctl stop docker
        sudo rm -rf /var/lib/docker
        sudo systemctl start docker
        echo "Docker used space:"
        sudo du -sh /var/lib/docker
        echo "Available storage:"
        df -h
    - id: cache-ivy2
      name: Cache Ivy packages
      uses: actions/cache@v4
      with:
        path: ~/.ivy2
        key: ${{ runner.os }}-ivy2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-ivy2
    - id: checkout-code
      name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.checkout-branch }}
    - id: setup-java
      name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{ inputs.java-version }}
        cache: maven
        server-id: sonatype-nexus
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
    - id: show-environment
      name: Show environment
      shell: bash
      run: |
        # Show environment
        echo ">>>> Operating system:"
        echo "  ${{ runner.os }}"
        echo ">>>> GitHub:"
        echo "  github.repository: ${{ github.repository }}"
        echo "  github.ref: ${{ github.head_ref || github.ref }}"
        echo "  github.sha: ${{ github.sha }}"
        echo ">>>> Java:"
        java -version
        echo ">>>> Maven:"
        mvn -v
        echo ">>>> Maven settings.xml:"
        cat ~/.m2/settings.xml ; echo
        echo ">>>> Maven toolchains.xml:"
        cat ~/.m2/toolchains.xml ; echo
        echo ">>>> Graphviz:"
        which dot || echo "Graphviz not installed"
        echo
